# Generated by Django 6.0 on 2025-12-29 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_table', models.CharField(max_length=10, unique=True)),
                ('nombre_places', models.PositiveIntegerField()),
                ('etat', models.CharField(choices=[('libre', 'Libre'), ('attente', 'Commande en attente'), ('servie', 'Commande servie'), ('payee', 'Commande payée')], default='libre', max_length=10)),
                ('utilisateur', models.OneToOneField(limit_choices_to={'role': 'Rtable'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
