# Generated by Django 6.0 on 2025-12-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('categorie', models.CharField(choices=[('ENTREE', 'Entrée'), ('PLAT', 'Plat'), ('DESSERT', 'Dessert'), ('BOISSON', 'Boisson')], max_length=10)),
                ('disponible', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='plats/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
