# Generated by Django 6.0 on 2026-01-03 13:33

import django.core.validators
import menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_plat_prix_commande_commandeitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plat',
            options={'ordering': ['categorie', 'nom'], 'verbose_name': 'Plat', 'verbose_name_plural': 'Plats'},
        ),
        migrations.AddField(
            model_name='plat',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='plat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=menu.models.plat_image_path),
        ),
        migrations.AlterField(
            model_name='plat',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
